github.com:
    users:
        TMCooper:
            oauth_token: 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
    git_protocol: https
    user: TMCooper
    oauth_token: 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
