general {
    hide_cursor = true
}

background {
    monitor =
    color = rgb(24, 24, 37)
}

input-field {
    monitor =
    size = 280, 45
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgb(203, 166, 247)
    inner_color = rgb(49, 50, 68)
    font_color = rgb(205, 214, 244)
    placeholder_text = Password...
    position = 0, 0
    halign = center
    valign = center
}